---
version: 1.0

graphite:
  host: 127.0.0.1
  port: 2003

receivers:
  homefan:
    type: kaku
    command: A 1

inputs:
  bathroom:
    type: DHT22
    pin: 4

rules:
  - when bathroom.humidity is greater than 57 then turn homefan on
  - when bathroom.humidity is less than 55 then turn homefan off
