---
version: 1.0

graphite:
  host: 127.0.0.1
  port: 2003
  enabled: true

receivers:
  echosomething:
    type: ToolCommandReceiver
    command: echo
    args: ${name} is now ${state}
    intools: false

  notification:
    type: ProwlReceiver
    api-key: <MY-Awesome-Prowl-api-key>
    application: homeautomation
    any-state: true

  homefan:
    type: KlikAanKlikUitReceiver
    address: A
    device: 1

inputs:
  bathroom:
    type: DHT22
    pin: 4

rules:
  - when bathroom.humidity is greater than 57 then turn homefan on and send notification "Homefan is on" and print echosomething on
  - when bathroom.humidity is less than 55 then turn homefan off and send notification "Homefan is off" and print echosomething off
  - every day at 22:00 turn homefan on
  - every day at 22:01 turn homefan off